services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    env_file: searxng.env
    networks:
      - searxng
      - caddy
    volumes:
      - searxng:/etc/searxng:rw
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
  searxng-valkey:
    container_name: searxng-valkey
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - searxng-valkey:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

networks:
  searxng:
    name: searxng
  caddy:
    external: true

volumes:
  searxng:
    name: searxng
  searxng-valkey:
    name: searxng-valkey