services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    runtime: nvidia
    restart: unless-stopped
    devices:
      - /dev/apex_0:/dev/apex_0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #      - /mnt/nvr-recordings:/media/frigate
      - frigate:/config
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - caddy
    ports:
      - "8555:8555/tcp"
      - "8555:8555/udp"

volumes:
  frigate:
    name: frigate

networks:
  caddy:
    external: true