name: CoreDNS
services:
  coredns:
    # https://hub.docker.com/r/coredns/coredns/
    image: coredns/coredns
    container_name: coredns
    restart: always
    command: -conf /etc/coredns/coredns.conf
    hostname: <HOSTNAME_GOES_HERE>
    user: 0:0
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./coredns.conf:/etc/coredns/coredns.conf
      - ./hosts.conf:/etc/coredns/hosts.conf
    ports:
      - 53:53
      - 53:53/udp