name: ComfyUi
services:
  comfyui:
    # https://github.com/YanWenKun/ComfyUI-Docker
    image: yanwk/comfyui-boot:cu128-slim
    container_name: comfyui
    restart: unless-stopped
    runtime: nvidia
    env_file: comfyui.env
    volumes:
      - comfyui:/root
    networks:
      - comfyui
    ports:
      - 8188:8188

volumes:
  comfyui:
    name: comfyui

networks:
  comfyui:
    name: comfyui